import pathlib,json,statistics,hashlib,math
root=pathlib.Path('/tmp/cartfoot_gate_read_20260908T061213Z');prov=json.loads((root/'provenance.json').read_text());groups=['walk/det','walk/sto','walk_startjitter/det','walk_startjitter/sto'];metrics=['slip_per_m','progress_ratio','along_dist_m','course_err_1s_med_deg','course_err_1s_p90_deg','direction_err_mean_deg','return'];reports={};out={'scope':'Exactly four 24-episode walk/walk_startjitter det+sto gates; excludes every mixed-session report. Descriptive paired results only, no formal verdict. Course aggregate means/medians are over per-episode statistics, not pooled control windows. Progress ratios above1 measure overspeed relative to commanded distance, not qualification.','reports':{},'pairs':{}}
def stats(rows):
 result={'episodes':len(rows),'gait_valid_count':sum(bool(e['gait_valid']) for e in rows),'termination_count':sum(bool(e['terminated']) for e in rows),'metrics':{}}
 for k in metrics:
  vals=[e[k] for e in rows];assert all(isinstance(v,(float,int)) and math.isfinite(v) for v in vals),(k,vals);result['metrics'][k]={'mean':statistics.mean(vals),'median':statistics.median(vals)}
 return result
for name in ['c1-cont10m','offctrl-cont10m','c1-s3','offctrl-s3']:
 f=root/(name+'_gate.json');r=json.loads(f.read_text());reports[name]=r;p=next(x for x in prov['runs'] if x['run'].endswith('-cartfoot-'+name));assert r['checkpoint']==p['checkpoint_path'];assert p['checkpoint_md5_current']==p['checkpoint_md5_manifest'];assert set(r['episodes'])==set(groups) and all(len(r['episodes'][g])==6 for g in groups);assert r['task']=='joint_walk';assert (r['model_source'],r['model_variant'],r['model_nmesh'],r['model_ngeom'],r['model_mass_kg'])==('mesh_mjx','mesh_mjx_twin',0,91,4.80573);m=r['motor_contract'];assert (m['bus.write_speed'],m['bus.write_acc'],m['safety.max_delta_q_deg'],m['control.hz'],m['resolved_vel_max_counts_s_max'])==(4096,1000,3.6,100,4096);flat=[e for g in groups for e in r['episodes'][g]];out['reports'][name]={'run':p['run'],'checkpoint':r['checkpoint'],'checkpoint_sha256_current':p['checkpoint_sha256_current'],'raw_gate_sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'model':{k:r[k] for k in ['model_source','model_variant','model_nmesh','model_ngeom','model_mass_kg']},'motor_contract':m,'training_seed':p['training_seed'],'eval_seed':r['seed'],'dr_scale_arg':r['dr_scale'],'policy_std':r['policy_std'],'randomization_note':'dr_scale argument0 does not disable explicit source DR overrides; episode randomization records are retained.','overall':stats(flat),'groups':{g:stats(r['episodes'][g]) for g in groups}}
for pair,on,off in [('cont10m','c1-cont10m','offctrl-cont10m'),('s3','c1-s3','offctrl-s3')]:
 a,b=reports[on],reports[off];pa=next(x for x in prov['runs'] if x['run'].endswith('-cartfoot-'+on));pb=next(x for x in prov['runs'] if x['run'].endswith('-cartfoot-'+off));ca,cb=pa['cfg'],pb['cfg'];expected={'goal.walk_cart_foot_box_x_m','goal.walk_cart_foot_box_y_m','goal.walk_cart_foot_box_z_m'};diffs={k:[ca.get(k),cb.get(k)] for k in ca.keys()|cb.keys() if ca.get(k)!=cb.get(k)};assert set(diffs)==expected;assert a['motor_contract']==b['motor_contract'];assert a['start_jitter_panel']==b['start_jitter_panel'];pairing={g:all(x['randomization']==y['randomization'] for x,y in zip(a['episodes'][g],b['episodes'][g])) for g in groups};p={'cfg_differences':diffs,'training_seed_matches':pa['training_seed']==pb['training_seed'],'motor_matches':True,'start_jitter_panel_matches':True,'episode_randomization_matches':pairing,'group_deltas_on_minus_off':{}}
 for g in groups:
  rows=[{k:x[k]-y[k] for k in metrics} for x,y in zip(a['episodes'][g],b['episodes'][g])];p['group_deltas_on_minus_off'][g]={k:{'mean':statistics.mean(e[k] for e in rows),'median':statistics.median(e[k] for e in rows)} for k in metrics}
 out['pairs'][pair]=p
out['provenance_limits']=prov['scope'];(root/'paired_summary.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:{'gait':v['overall']['gait_valid_count'],'terms':v['overall']['termination_count'],'slip':v['overall']['metrics']['slip_per_m'],'progress':v['overall']['metrics']['progress_ratio'],'course_1s_episode_median':v['overall']['metrics']['course_err_1s_med_deg']} for k,v in out['reports'].items()},indent=2));print('pairing', {k:v['episode_randomization_matches'] for k,v in out['pairs'].items()})
